// src/components/master/InputModal.tsx
import React, { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export interface InputModalProps {
  isOpen: boolean;
  title: string;
  label: string;
  initialValue: string;
  onConfirm: (value: string) => void;
  onCancel: () => void;
}

export const InputModal: React.FC<InputModalProps> = ({
  isOpen,
  title,
  label,
  initialValue,
  onConfirm,
  onCancel,
}) => {
  const [inputValue, setInputValue] = useState(initialValue);

  useEffect(() => {
    if (isOpen) {
      setInputValue(initialValue);
    }
  }, [isOpen, initialValue]);

  const handleConfirm = () => {
    const trimmed = inputValue.trim();
    if (!trimmed) return;
    onConfirm(trimmed);
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onCancel()}>
      <DialogContent className="sm:max-w-sm">
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
        </DialogHeader>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleConfirm();
          }}
          className="space-y-4"
        >
          <div className="space-y-2">
            <Label htmlFor="input-modal-field">{label}</Label>
            <Input
              id="input-modal-field"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              type="text"
              autoFocus
            />
          </div>

          <DialogFooter className="gap-2 sm:gap-0">
            <Button type="button" variant="outline" onClick={onCancel}>
              Batal
            </Button>
            <Button type="submit" disabled={!inputValue.trim()}>
              Simpan
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default InputModal;

// src/components/master/InputModal.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const props = defineProps<{
  isOpen: boolean;
  title: string;
  label: string;
  initialValue: string;
}>();

const emit = defineEmits<{
  (e: "confirm", value: string): void;
  (e: "cancel"): void;
}>();

const inputValue = ref("");

// Otomatis mengisi input dengan nama lama saat modal terbuka
watch(
  () => props.isOpen,
  (newVal) => {
    if (newVal) {
      inputValue.value = props.initialValue;
    }
  },
);

const handleConfirm = () => {
  if (!inputValue.value.trim()) return;
  emit("confirm", inputValue.value.trim());
};

const handleOpenChange = (open: boolean) => {
  if (!open) emit("cancel");
};
</script>

<template>
  <Dialog :open="isOpen" @update:open="handleOpenChange">
    <DialogContent class="sm:max-w-sm">
      <DialogHeader>
        <DialogTitle>{{ title }}</DialogTitle>
      </DialogHeader>

      <div class="space-y-2">
        <Label>{{ label }}</Label>
        <Input
          v-model="inputValue"
          @keyup.enter="handleConfirm"
          type="text"
        />
      </div>

      <DialogFooter>
        <Button
          type="button"
          variant="outline"
          @click="emit('cancel')"
        >
          Batal
        </Button>
        <Button
          type="button"
          @click="handleConfirm"
        >
          Simpan
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
