// src/components/master/SantriForm.vue
<script setup lang="ts">
import { ref } from "vue";
import { HugeiconsIcon } from "@hugeicons/vue";
import { PlusSignIcon } from "@hugeicons/core-free-icons";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { Jilid, Guru, SantriType } from "../../types";
import { terms } from "../../config/organization";

const props = defineProps<{
  jilidList: Jilid[];
  guruList: Guru[];
  tipeList: SantriType[];
  variant?: "card" | "plain";
}>();

const emit = defineEmits<{
  (
    e: "submit",
    data: {
      nama: string;
      jilidId: string;
      guruId: string;
      tipeId?: string;
      tanggalLahir?: string;
    },
  ): void;
  (e: "cancel"): void;
}>();

const inputNama = ref("");
const selectedJilid = ref("");
const selectedGuru = ref("");
const selectedTipe = ref("");
const selectedTanggalLahir = ref("");

const handleSubmit = () => {
  if (!inputNama.value || !selectedJilid.value || !selectedGuru.value) {
    return alert("Lengkapi data terlebih dahulu");
  }

  emit("submit", {
    nama: inputNama.value,
    jilidId: selectedJilid.value,
    guruId: selectedGuru.value,
    tipeId: selectedTipe.value || undefined,
    tanggalLahir: selectedTanggalLahir.value || undefined,
  });

  inputNama.value = ""; // Reset form setelah submit
  selectedTanggalLahir.value = "";
};
</script>

<template>
  <component
    :is="props.variant === 'plain' ? 'form' : Card"
    :class="props.variant === 'plain' ? 'space-y-4' : 'gap-0 py-0'"
    @submit.prevent="handleSubmit"
  >
    <CardHeader v-if="props.variant !== 'plain'" class="border-b py-4">
      <CardTitle>Tambah {{ terms.studentSingularTitle }} Baru</CardTitle>
    </CardHeader>

    <div :class="props.variant === 'plain' ? 'space-y-4' : 'space-y-4 p-4'">
      <div>
        <Label>
          Nama {{ terms.studentSingularTitle }}
        </Label>
        <Textarea
          v-model="inputNama"
          placeholder="Pisahkan dengan koma (contoh: Budi, Andi)"
          rows="2"
        />
      </div>

      <div class="flex gap-3">
        <div class="w-full">
          <Label>
            {{ terms.levelSingularTitle }}
          </Label>
          <select
            v-model="selectedJilid"
            class="ui-select"
          >
            <option value="" disabled>
              Pilih {{ terms.levelSingularTitle }}
            </option>
            <option
              v-for="jilid in jilidList"
              :key="jilid.id"
              :value="jilid.id"
            >
              {{ jilid.nama }}
            </option>
          </select>
        </div>
        <div class="w-full">
          <Label>
            {{ terms.mentorSingularTitle }}
          </Label>
          <select
            v-model="selectedGuru"
            class="ui-select"
          >
            <option value="" disabled>
              Pilih {{ terms.mentorSingularTitle }}
            </option>
            <option v-for="guru in guruList" :key="guru.id" :value="guru.id">
              {{ guru.nama }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <Label>Tipe {{ terms.studentSingularTitle }}</Label>
        <select
          v-model="selectedTipe"
          class="ui-select"
        >
          <option value="">Tanpa tipe</option>
          <option
            v-for="tipe in tipeList"
            :key="tipe.id"
            :value="tipe.id"
          >
            {{ tipe.nama }}
          </option>
        </select>
      </div>

      <div>
        <Label>Tanggal Lahir</Label>
        <input
          v-model="selectedTanggalLahir"
          type="date"
          class="ui-input"
        />
      </div>

      <div class="pt-2">
        <Button
          type="button"
          class="w-full md:w-auto"
          @click="handleSubmit"
        >
          <HugeiconsIcon
            :icon="PlusSignIcon"
            :size="17"
            color="currentColor"
            :stroke-width="2"
          />
          Simpan Data
        </Button>
      </div>
    </div>
  </component>
</template>

// src/components/master/SantriForm.tsx
import React, { useState } from "react";
import { HugeiconsIcon } from "@hugeicons/react";
import { PlusSignIcon } from "@hugeicons/core-free-icons";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { Guru, Jilid, SantriType } from "@/types";
import { useTerms } from "@/config/organization";

export interface SantriFormPayload {
  nama: string;
  jilidId: string;
  guruId: string;
  tipeId?: string;
  tanggalLahir?: string;
  tanggalMasuk?: string;
}

export interface SantriFormProps {
  jilidList: Jilid[];
  guruList: Guru[];
  tipeList: SantriType[];
  variant?: "card" | "plain";
  onSubmit: (data: SantriFormPayload) => void;
  onCancel?: () => void;
}

export const SantriForm: React.FC<SantriFormProps> = ({
  jilidList,
  guruList,
  tipeList,
  variant = "card",
  onSubmit,
}) => {
  const terms = useTerms();
  const [inputNama, setInputNama] = useState("");
  const [selectedJilid, setSelectedJilid] = useState("");
  const [selectedGuru, setSelectedGuru] = useState("");
  const [selectedTipe, setSelectedTipe] = useState("");
  const [selectedTanggalLahir, setSelectedTanggalLahir] = useState("");
  const [selectedTanggalMasuk, setSelectedTanggalMasuk] = useState(() =>
    new Date().toISOString().slice(0, 10)
  );

  const handleSubmit = (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!inputNama.trim() || !selectedJilid || !selectedGuru) {
      alert("Lengkapi data terlebih dahulu");
      return;
    }

    onSubmit({
      nama: inputNama.trim(),
      jilidId: selectedJilid,
      guruId: selectedGuru,
      tipeId: selectedTipe || undefined,
      tanggalLahir: selectedTanggalLahir || undefined,
      tanggalMasuk: selectedTanggalMasuk || undefined,
    });

    setInputNama("");
    setSelectedTanggalLahir("");
    setSelectedTanggalMasuk(new Date().toISOString().slice(0, 10));
  };

  const formContent = (
    <div className={variant === "plain" ? "space-y-4" : "space-y-4 p-4"}>
      <div>
        <Label htmlFor="santri-names-input">
          Nama {terms.studentSingularTitle}
        </Label>
        <Textarea
          id="santri-names-input"
          value={inputNama}
          onChange={(e) => setInputNama(e.target.value)}
          placeholder="Pisahkan dengan koma (contoh: Budi, Andi)"
          rows={2}
        />
      </div>

      <div className="flex gap-3">
        <div className="w-full">
          <Label htmlFor="santri-jilid-select">
            {terms.levelSingularTitle}
          </Label>
          <select
            id="santri-jilid-select"
            value={selectedJilid}
            onChange={(e) => setSelectedJilid(e.target.value)}
            className="ui-select"
          >
            <option value="" disabled>
              Pilih {terms.levelSingularTitle}
            </option>
            {jilidList.map((jilid) => (
              <option key={jilid.id} value={jilid.id}>
                {jilid.nama}
              </option>
            ))}
          </select>
        </div>

        <div className="w-full">
          <Label htmlFor="santri-guru-select">
            {terms.mentorSingularTitle}
          </Label>
          <select
            id="santri-guru-select"
            value={selectedGuru}
            onChange={(e) => setSelectedGuru(e.target.value)}
            className="ui-select"
          >
            <option value="" disabled>
              Pilih {terms.mentorSingularTitle}
            </option>
            {guruList.map((guru) => (
              <option key={guru.id} value={guru.id}>
                {guru.nama}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div>
        <Label htmlFor="santri-tipe-select">
          Tipe {terms.studentSingularTitle}
        </Label>
        <select
          id="santri-tipe-select"
          value={selectedTipe}
          onChange={(e) => setSelectedTipe(e.target.value)}
          className="ui-select"
        >
          <option value="">Tanpa tipe</option>
          {tipeList.map((tipe) => (
            <option key={tipe.id} value={tipe.id}>
              {tipe.nama}
            </option>
          ))}
        </select>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div>
          <Label htmlFor="santri-entrydate-input">Tanggal Masuk</Label>
          <input
            id="santri-entrydate-input"
            value={selectedTanggalMasuk}
            onChange={(e) => setSelectedTanggalMasuk(e.target.value)}
            type="date"
            className="ui-input"
          />
        </div>

        <div>
          <Label htmlFor="santri-birthdate-input">Tanggal Lahir</Label>
          <input
            id="santri-birthdate-input"
            value={selectedTanggalLahir}
            onChange={(e) => setSelectedTanggalLahir(e.target.value)}
            type="date"
            className="ui-input"
          />
        </div>
      </div>

      <div className="pt-2">
        <Button type="submit" className="w-full md:w-auto">
          <HugeiconsIcon
            icon={PlusSignIcon}
            size={17}
            color="currentColor"
            strokeWidth={2}
          />
          Simpan Data
        </Button>
      </div>
    </div>
  );

  if (variant === "plain") {
    return (
      <form onSubmit={handleSubmit} className="space-y-4">
        {formContent}
      </form>
    );
  }

  return (
    <Card className="gap-0 py-0">
      <CardHeader className="border-b py-4">
        <CardTitle>Tambah {terms.studentSingularTitle} Baru</CardTitle>
      </CardHeader>
      <form onSubmit={handleSubmit}>{formContent}</form>
    </Card>
  );
};

export default SantriForm;
