// src/components/master/Toast.tsx
import React, { useEffect } from "react";
import { AnimatePresence, motion } from "motion/react";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  CancelCircleIcon,
  CheckmarkCircle02Icon,
} from "@hugeicons/core-free-icons";
import { springDefault, useSmoothMotion } from "@/lib/motion";

export interface ToastProps {
  show: boolean;
  message: string;
  type?: "success" | "error";
  duration?: number;
  onClose: () => void;
}

export const Toast: React.FC<ToastProps> = ({
  show,
  message,
  type = "success",
  duration = 3000,
  onClose,
}) => {
  const { shouldReduceMotion } = useSmoothMotion();

  useEffect(() => {
    if (!show) return;

    const timer = window.setTimeout(() => {
      onClose();
    }, duration);

    return () => {
      window.clearTimeout(timer);
    };
  }, [show, duration, onClose]);

  return (
    <AnimatePresence>
      {show && (
        <motion.div
          role="status"
          aria-live="polite"
          initial={
            shouldReduceMotion
              ? { opacity: 0 }
              : { opacity: 0, y: 14, scale: 0.96 }
          }
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={
            shouldReduceMotion
              ? { opacity: 0 }
              : { opacity: 0, y: 10, scale: 0.96 }
          }
          transition={
            shouldReduceMotion
              ? { duration: 0.15 }
              : springDefault
          }
          className="fixed bottom-20 left-1/2 -translate-x-1/2 z-[100] w-max max-w-[90vw] pointer-events-none"
        >
          <div className="bg-[#202223] text-white text-[13px] px-4 py-2.5 rounded-full shadow-xl flex items-center gap-2 pointer-events-auto">
            {type !== "error" ? (
              <HugeiconsIcon
                icon={CheckmarkCircle02Icon}
                size={16}
                color="#008060"
                strokeWidth={2}
              />
            ) : (
              <HugeiconsIcon
                icon={CancelCircleIcon}
                size={16}
                color="#D72C0D"
                strokeWidth={2}
              />
            )}
            <span className="truncate font-medium">{message}</span>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default Toast;

// src/components/master/Toast.vue
<script setup lang="ts">
import { watch } from "vue";
import { HugeiconsIcon } from "@hugeicons/vue";
import {
  CancelCircleIcon,
  CheckmarkCircle02Icon,
} from "@hugeicons/core-free-icons";

const props = defineProps<{
  show: boolean;
  message: string;
  type?: "success" | "error";
  duration?: number;
}>();

const emit = defineEmits(["close"]);

// Gunakan watch agar setiap kali show berubah jadi true, timer jalan lagi
watch(
  () => props.show,
  (newVal) => {
    if (newVal) {
      setTimeout(() => {
        emit("close");
      }, props.duration || 3000);
    }
  },
);
</script>

<template>
  <Transition
    enter-active-class="transform ease-out duration-300 transition"
    enter-from-class="translate-y-2 opacity-0"
    enter-to-class="translate-y-0 opacity-100"
    leave-active-class="transition ease-in duration-100"
    leave-from-class="opacity-100"
    leave-to-class="opacity-0"
  >
    <!-- Tambahkan v-if agar transisi bekerja -->
    <div
      v-if="show"
      class="fixed bottom-20 left-1/2 -translate-x-1/2 z-[100] w-max"
    >
      <div
        class="bg-[#202223] text-white text-[13px] px-4 py-2 rounded-full shadow-lg flex items-center gap-2"
      >
        <HugeiconsIcon
          v-if="type !== 'error'"
          :icon="CheckmarkCircle02Icon"
          :size="16"
          color="#008060"
          :stroke-width="2"
        />
        <HugeiconsIcon
          v-else
          :icon="CancelCircleIcon"
          :size="16"
          color="#D72C0D"
          :stroke-width="2"
        />
        {{ message }}
      </div>
    </div>
  </Transition>
</template>
