// src/views/AbsensiView.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { useRouter } from "vue-router";
import { getSantri, getJilid } from "../services/masterService";
import {
  saveAttendance,
  listenAttendanceByDate,
  type Unsubscribe,
} from "../services/attendanceService";
import type { Santri, Jilid, Attendance, AttendanceStatus } from "../types";
// import { useRoute } from "vue-router"; // Dihapus jika tidak digunakan

// Import komponen-komponen kecil
import AbsensiFilter from "../components/absensi/AbsensiFilter.vue";
import AbsensiList from "../components/absensi/AbsensiList.vue";
import DailyRecapButton from "../components/absensi/DailyRecapButton.vue";
import Toast from "../components/master/Toast.vue";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { hasSeenAccountSetupOnboarding } from "../services/onboardingService";

const router = useRouter();

// 🛠️ HELPER: Dapatkan tanggal sesuai Local Timezone Device (Format: YYYY-MM-DD)
const getLocalDateString = () => {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

// State Tanggal
const todayDate = computed(() => getLocalDateString());
const currentDate = ref<string>(getLocalDateString());

// State Data & UI
const selectedJilid = ref("Semua");
const santriList = ref<Santri[]>([]);
const jilidList = ref<Jilid[]>([]);
const attendanceData = ref<Attendance[]>([]);
const savingSantriIds = ref<Set<string>>(new Set());
const isSetupOnboardingOpen = ref(false);
let unsubscribeAttendance: Unsubscribe | null = null;

// State Toast
const showToast = ref(false);
const toastMessage = ref("");
const toastType = ref<"success" | "error">("success");

const triggerToast = (msg: string, type: "success" | "error" = "success") => {
  toastMessage.value = msg;
  toastType.value = type;
  showToast.value = true;
};

// Handle page visibility: Refresh tanggal saat tab kembali dibuka
const handleVisibilityChange = () => {
  if (document.visibilityState === "visible") {
    currentDate.value = getLocalDateString();
  }
};

onMounted(async () => {
  // Pasang listener saat komponen dipasang
  document.addEventListener("visibilitychange", handleVisibilityChange);

  try {
    // Ambil master data secara paralel (lebih cepat)
    const [santriRes, jilidRes] = await Promise.all([getSantri(), getJilid()]);
    santriList.value = santriRes;
    jilidList.value = jilidRes;
    isSetupOnboardingOpen.value = !(await hasSeenAccountSetupOnboarding());
  } catch (error) {
    triggerToast("Koneksi bermasalah. Data belum bisa dimuat.", "error");
  }
});

onUnmounted(() => {
  resetAttendanceListener();
  document.removeEventListener("visibilitychange", handleVisibilityChange);
});

const resetAttendanceListener = () => {
  if (unsubscribeAttendance) {
    unsubscribeAttendance();
    unsubscribeAttendance = null;
  }
};

// Listener Firebase berdasarkan tanggal
const listenCurrentDateAttendance = async () => {
  resetAttendanceListener();

  if (currentDate.value > todayDate.value) {
    currentDate.value = todayDate.value;
    triggerToast("Tanggal tidak boleh melebihi hari ini.", "error");
    return;
  }

  unsubscribeAttendance = await listenAttendanceByDate(
    currentDate.value,
    (data) => {
      attendanceData.value = data;
    },
    () => {
      triggerToast("Koneksi bermasalah. Absensi gagal dimuat.", "error");
    },
  );
};

// Pantau perubahan currentDate
watch(currentDate, listenCurrentDateAttendance, { immediate: true });

// Formatter Tanggal UI (contoh: Senin, 16 Mei 2026)
const formattedDate = computed(() => {
  const date = new Date(currentDate.value + "T00:00:00");
  return date.toLocaleDateString("id-ID", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
});

// Fitur 1: Sorting Alphabet dan Filter Jilid
const filteredSantri = computed(() => {
  let list = santriList.value.filter((s) => s.isActive);
  if (selectedJilid.value !== "Semua") {
    list = list.filter((s) => s.jilidId === selectedJilid.value);
  }
  return list.sort((a, b) => a.nama.localeCompare(b.nama));
});

// Ringkasan Absensi
const attendanceSummary = computed(() => {
  const total = filteredSantri.value.length;
  let present = 0;
  let permission = 0;

  filteredSantri.value.forEach((santri) => {
    const record = attendanceData.value.find((a) => a.santriId === santri.id);
    if (!record) return;
    const status = record.status ?? (record.isPresent ? "present" : "absent");
    if (status === "present") present += 1;
    if (status === "permission") permission += 1;
  });

  return {
    total,
    present,
    permission,
    unmarked: total - present - permission,
  };
});

// Handle Ubah Status Absensi
const handleStatusChange = async (santri: Santri, status: AttendanceStatus) => {
  const previousData = attendanceData.value.map((item) => ({ ...item }));
  let record = attendanceData.value.find((a) => a.santriId === santri.id);

  const currentStatus =
    record?.status ?? (record?.isPresent ? "present" : "absent");
  const nextStatus: AttendanceStatus =
    currentStatus === status ? "absent" : status;
  const isPresent = nextStatus === "present";

  // Optimistic UI Update (Update UI seketika sebelum tunggu server)
  if (record) {
    record.isPresent = isPresent;
    record.status = nextStatus;
  } else {
    attendanceData.value.push({
      id: "",
      date: currentDate.value,
      santriId: santri.id,
      jilidId: santri.jilidId,
      guruId: santri.guruId,
      isPresent,
      status: nextStatus,
    });
  }

  savingSantriIds.value.add(santri.id);

  try {
    await saveAttendance({
      date: currentDate.value,
      santriId: santri.id,
      jilidId: santri.jilidId,
      guruId: santri.guruId,
      isPresent,
      status: nextStatus,
    });
  } catch (error) {
    // Rollback jika gagal API
    attendanceData.value = previousData;
    triggerToast("Koneksi bermasalah. Absensi gagal disimpan.", "error");
  } finally {
    savingSantriIds.value.delete(santri.id);
  }
};

const goToAccountSetup = () => {
  isSetupOnboardingOpen.value = false;
  router.push({
    path: "/akun",
    query: { onboarding: "setup" },
  });
};
</script>

<template>
  <div class="app-page">
    <header class="app-container app-header pb-4">
      <div>
        <h1 class="app-title">Absensi Harian</h1>
        <p class="app-subtitle">
          {{ formattedDate }}
        </p>
      </div>
      <!-- Cukup gunakan v-model, vue otomatis urus event @change -->
      <Input
        type="date"
        v-model="currentDate"
        :max="todayDate"
        autocomplete="off"
        class="w-auto cursor-pointer font-medium"
      />
    </header>

    <div class="app-container space-y-5">
      <div class="space-y-3">
        <AbsensiFilter
          :jilidList="jilidList"
          v-model:selectedJilid="selectedJilid"
        />

        <!-- Komponen Tombol Rekap Harian (Fitur 2) -->
        <DailyRecapButton
          :filteredSantri="filteredSantri"
          :attendanceData="attendanceData"
          @success="triggerToast"
          @error="(msg) => triggerToast(msg, 'error')"
        />
      </div>

      <div
        class="grid grid-cols-3 gap-2 sm:gap-3"
        aria-label="Ringkasan absensi"
      >
        <div
          class="rounded-lg border border-[hsl(142_42%_82%)] bg-[hsl(142_76%_97%)] p-2.5 sm:p-3"
        >
          <p class="text-xs text-[hsl(142_72%_29%)]">Hadir</p>
          <p class="text-xl font-bold text-[hsl(142_72%_29%)]">
            {{ attendanceSummary.present }}
          </p>
        </div>
        <div
          class="rounded-lg border border-[hsl(48_76%_78%)] bg-[hsl(48_96%_97%)] p-2.5 sm:p-3"
        >
          <p class="text-xs text-[hsl(32_95%_35%)]">Izin</p>
          <p class="text-xl font-bold text-[hsl(32_95%_35%)]">
            {{ attendanceSummary.permission }}
          </p>
        </div>
        <div class="rounded-lg border bg-muted p-2.5 sm:p-3">
          <p class="text-xs text-muted-foreground">Belum diabsen</p>
          <p class="text-xl font-bold text-foreground">
            {{ attendanceSummary.unmarked }}
          </p>
        </div>
      </div>

      <AbsensiList
        :filteredSantri="filteredSantri"
        :jilidList="jilidList"
        :attendanceData="attendanceData"
        :savingSantriIds="savingSantriIds"
        @status-change="handleStatusChange"
      />
    </div>

    <Toast
      :show="showToast"
      :message="toastMessage"
      :type="toastType"
      @close="showToast = false"
    />

    <Dialog :open="isSetupOnboardingOpen">
      <DialogContent class="sm:max-w-md" :show-close-button="false">
        <DialogHeader>
          <DialogTitle>Selamat Datang</DialogTitle>
          <DialogDescription>
            Silakan lengkapi pengaturan aplikasi di halaman akun sebelum mulai
            mengelola data.
          </DialogDescription>
        </DialogHeader>

        <Button type="button" class="w-full" @click="goToAccountSetup">
          Buka Pengaturan Akun
        </Button>
      </DialogContent>
    </Dialog>
  </div>
</template>

// src/views/AbsensiView.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getSantri, getJilid } from "@/services/masterService";
import {
  saveAttendance,
  listenAttendanceByDate,
  type Unsubscribe,
} from "@/services/attendanceService";
import { hasSeenAccountSetupOnboarding } from "@/services/onboardingService";
import type { Attendance, AttendanceStatus, Jilid, Santri } from "@/types";
import AbsensiFilter from "@/components/absensi/AbsensiFilter";
import AbsensiList from "@/components/absensi/AbsensiList";
import DailyRecapButton from "@/components/absensi/DailyRecapButton";
import Toast from "@/components/master/Toast";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

const getLocalDateString = () => {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

export const AbsensiView: React.FC = () => {
  const navigate = useNavigate();

  const [todayDate] = useState(() => getLocalDateString());
  const [currentDate, setCurrentDate] = useState(() => getLocalDateString());

  const [selectedJilid, setSelectedJilid] = useState("Semua");
  const [santriList, setSantriList] = useState<Santri[]>([]);
  const [jilidList, setJilidList] = useState<Jilid[]>([]);
  const [attendanceData, setAttendanceData] = useState<Attendance[]>([]);
  const [savingSantriIds, setSavingSantriIds] = useState<Set<string>>(
    () => new Set(),
  );
  const [isSetupOnboardingOpen, setIsSetupOnboardingOpen] = useState(false);

  const [toast, setToast] = useState<{
    show: boolean;
    message: string;
    type: "success" | "error";
  }>({
    show: false,
    message: "",
    type: "success",
  });

  const triggerToast = useCallback(
    (message: string, type: "success" | "error" = "success") => {
      setToast({ show: true, message, type });
    },
    [],
  );

  const attendanceDataRef = useRef<Attendance[]>(attendanceData);
  attendanceDataRef.current = attendanceData;

  // Handle visibility change
  useEffect(() => {
    const handleVisibility = () => {
      if (document.visibilityState === "visible") {
        setCurrentDate(getLocalDateString());
      }
    };
    document.addEventListener("visibilitychange", handleVisibility);
    return () => {
      document.removeEventListener("visibilitychange", handleVisibility);
    };
  }, []);

  // Load initial master data
  useEffect(() => {
    let isMounted = true;
    const loadMaster = async () => {
      try {
        const [santriRes, jilidRes, hasSeenOnboarding] = await Promise.all([
          getSantri(),
          getJilid(),
          hasSeenAccountSetupOnboarding(),
        ]);
        if (!isMounted) return;
        setSantriList(santriRes);
        setJilidList(jilidRes);
        setIsSetupOnboardingOpen(!hasSeenOnboarding);
      } catch {
        if (isMounted) {
          triggerToast("Koneksi bermasalah. Data belum bisa dimuat.", "error");
        }
      }
    };

    void loadMaster();
    return () => {
      isMounted = false;
    };
  }, [triggerToast]);

  // Subscribe to attendance by date
  useEffect(() => {
    let unsubscribe: Unsubscribe | null = null;
    let isCancelled = false;

    if (currentDate > todayDate) {
      setCurrentDate(todayDate);
      triggerToast("Tanggal tidak boleh melebihi hari ini.", "error");
      return;
    }

    const startListener = async () => {
      try {
        const unsub = await listenAttendanceByDate(
          currentDate,
          (data) => {
            if (!isCancelled) {
              setAttendanceData(data);
            }
          },
          () => {
            if (!isCancelled) {
              triggerToast(
                "Koneksi bermasalah. Absensi gagal dimuat.",
                "error",
              );
            }
          },
        );
        if (isCancelled) {
          unsub();
        } else {
          unsubscribe = unsub;
        }
      } catch {
        if (!isCancelled) {
          triggerToast("Koneksi bermasalah. Absensi gagal dimuat.", "error");
        }
      }
    };

    void startListener();

    return () => {
      isCancelled = true;
      if (unsubscribe) {
        unsubscribe();
      }
    };
  }, [currentDate, todayDate, triggerToast]);

  const formattedDate = useMemo(() => {
    const date = new Date(currentDate + "T00:00:00");
    return date.toLocaleDateString("id-ID", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  }, [currentDate]);

  const filteredSantri = useMemo(() => {
    let list = santriList.filter((s) => s.isActive);
    if (selectedJilid !== "Semua") {
      list = list.filter((s) => s.jilidId === selectedJilid);
    }
    return list.slice().sort((a, b) => a.nama.localeCompare(b.nama));
  }, [santriList, selectedJilid]);

  const attendanceSummary = useMemo(() => {
    const total = filteredSantri.length;
    let present = 0;
    let permission = 0;

    const map = new Map(attendanceData.map((a) => [a.santriId, a]));

    filteredSantri.forEach((santri) => {
      const record = map.get(santri.id);
      if (!record) return;
      const status =
        record.status ?? (record.isPresent ? "present" : "absent");
      if (status === "present") present += 1;
      if (status === "permission") permission += 1;
    });

    return {
      total,
      present,
      permission,
      unmarked: total - present - permission,
    };
  }, [filteredSantri, attendanceData]);

  const handleStatusChange = useCallback(
    async (santri: Santri, status: AttendanceStatus) => {
      const previousData = attendanceDataRef.current.map((item) => ({
        ...item,
      }));
      const existingRecord = attendanceDataRef.current.find(
        (a) => a.santriId === santri.id,
      );

      const currentStatus =
        existingRecord?.status ??
        (existingRecord?.isPresent ? "present" : "absent");
      const nextStatus: AttendanceStatus =
        currentStatus === status ? "absent" : status;
      const isPresent = nextStatus === "present";

      // Optimistic update
      setAttendanceData((prev) => {
        const found = prev.find((a) => a.santriId === santri.id);
        if (found) {
          return prev.map((item) =>
            item.santriId === santri.id
              ? { ...item, isPresent, status: nextStatus }
              : item,
          );
        } else {
          return [
            ...prev,
            {
              id: "",
              date: currentDate,
              santriId: santri.id,
              jilidId: santri.jilidId,
              guruId: santri.guruId,
              isPresent,
              status: nextStatus,
            },
          ];
        }
      });

      setSavingSantriIds((prev) => new Set(prev).add(santri.id));

      try {
        await saveAttendance({
          date: currentDate,
          santriId: santri.id,
          jilidId: santri.jilidId,
          guruId: santri.guruId,
          isPresent,
          status: nextStatus,
        });
      } catch {
        setAttendanceData(previousData);
        triggerToast("Koneksi bermasalah. Absensi gagal disimpan.", "error");
      } finally {
        setSavingSantriIds((prev) => {
          const next = new Set(prev);
          next.delete(santri.id);
          return next;
        });
      }
    },
    [currentDate, triggerToast],
  );

  const goToAccountSetup = () => {
    setIsSetupOnboardingOpen(false);
    navigate({
      pathname: "/akun",
      search: "?onboarding=setup",
    });
  };

  return (
    <div className="app-page">
      <header className="app-container app-header pb-4">
        <div>
          <h1 className="app-title">Absensi Harian</h1>
          <p className="app-subtitle">{formattedDate}</p>
        </div>
        <Input
          type="date"
          value={currentDate}
          max={todayDate}
          autoComplete="off"
          onChange={(e) => setCurrentDate(e.target.value)}
          className="w-auto cursor-pointer font-medium"
        />
      </header>

      <div className="app-container space-y-5">
        <div className="space-y-3">
          <AbsensiFilter
            jilidList={jilidList}
            selectedJilid={selectedJilid}
            onSelectJilid={setSelectedJilid}
          />

          <DailyRecapButton
            filteredSantri={filteredSantri}
            attendanceData={attendanceData}
            onSuccess={(msg) => triggerToast(msg, "success")}
            onError={(msg) => triggerToast(msg, "error")}
          />
        </div>

        <div
          className="grid grid-cols-3 gap-2 sm:gap-3"
          aria-label="Ringkasan absensi"
        >
          <div className="rounded-lg border border-[hsl(142_42%_82%)] bg-[hsl(142_76%_97%)] p-2.5 sm:p-3">
            <p className="text-xs text-[hsl(142_72%_29%)]">Hadir</p>
            <p className="text-xl font-bold text-[hsl(142_72%_29%)]">
              {attendanceSummary.present}
            </p>
          </div>
          <div className="rounded-lg border border-[hsl(48_76%_78%)] bg-[hsl(48_96%_97%)] p-2.5 sm:p-3">
            <p className="text-xs text-[hsl(32_95%_35%)]">Izin</p>
            <p className="text-xl font-bold text-[hsl(32_95%_35%)]">
              {attendanceSummary.permission}
            </p>
          </div>
          <div className="rounded-lg border border-border bg-muted p-2.5 sm:p-3">
            <p className="text-xs text-muted-foreground">Belum diabsen</p>
            <p className="text-xl font-bold text-foreground">
              {attendanceSummary.unmarked}
            </p>
          </div>
        </div>

        <AbsensiList
          filteredSantri={filteredSantri}
          jilidList={jilidList}
          attendanceData={attendanceData}
          savingSantriIds={savingSantriIds}
          onStatusChange={handleStatusChange}
        />
      </div>

      <Toast
        show={toast.show}
        message={toast.message}
        type={toast.type}
        onClose={() => setToast((prev) => ({ ...prev, show: false }))}
      />

      <Dialog open={isSetupOnboardingOpen}>
        <DialogContent className="sm:max-w-md" showCloseButton={false}>
          <DialogHeader>
            <DialogTitle>Selamat Datang</DialogTitle>
            <DialogDescription>
              Silakan lengkapi pengaturan aplikasi di halaman akun sebelum
              mulai mengelola data.
            </DialogDescription>
          </DialogHeader>

          <Button type="button" className="w-full" onClick={goToAccountSetup}>
            Buka Pengaturan Akun
          </Button>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default AbsensiView;
