// src/components/common/PaginationControls.tsx
import React from "react";
import { Button } from "@/components/ui/button";

export interface PaginationControlsProps {
  currentPage: number;
  totalPages: number;
  totalItems: number;
  visibleStart: number;
  visibleEnd: number;
  itemLabel?: string;
  onPageChange: (page: number) => void;
}

export const PaginationControls: React.FC<PaginationControlsProps> = ({
  currentPage,
  totalPages,
  totalItems,
  visibleStart,
  visibleEnd,
  itemLabel = "data",
  onPageChange,
}) => {
  if (totalItems <= 0) return null;

  return (
    <div className="p-4 border-t border-border flex flex-col gap-3 bg-muted/40 sm:flex-row sm:items-center sm:justify-between">
      <p className="text-[12px] text-muted-foreground">
        Menampilkan {visibleStart}-{visibleEnd} dari {totalItems} {itemLabel}
      </p>

      <div className="flex items-center gap-2">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => onPageChange(currentPage - 1)}
          disabled={currentPage <= 1}
        >
          Sebelumnya
        </Button>
        <span className="text-[13px] text-muted-foreground">
          Halaman {currentPage} / {totalPages || 1}
        </span>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => onPageChange(currentPage + 1)}
          disabled={currentPage >= totalPages}
        >
          Berikutnya
        </Button>
      </div>
    </div>
  );
};

export default PaginationControls;

// src/components/common/PaginationControls.vue
<script setup lang="ts">
defineProps<{
  currentPage: number;
  totalPages: number;
  totalItems: number;
  visibleStart: number;
  visibleEnd: number;
  itemLabel?: string;
}>();

const emit = defineEmits<{
  (e: "update:currentPage", page: number): void;
}>();
</script>

<template>
  <div
    v-if="totalItems > 0"
    class="p-4 border-t border-[#E1E3E5] flex flex-col gap-3 bg-[#FAFAFA] sm:flex-row sm:items-center sm:justify-between"
  >
    <p class="text-[12px] text-[#6D7175]">
      Menampilkan {{ visibleStart }}-{{ visibleEnd }} dari {{ totalItems }}
      {{ itemLabel || "data" }}
    </p>

    <div class="flex items-center gap-2">
      <button
        type="button"
        @click="emit('update:currentPage', currentPage - 1)"
        :disabled="currentPage === 1"
        class="px-3 py-1.5 rounded-md text-[13px] font-medium border border-[#C9CCCF] bg-white text-[#202223] disabled:opacity-50 disabled:cursor-not-allowed"
      >
        Sebelumnya
      </button>
      <span class="text-[13px] text-[#454749]">
        Halaman {{ currentPage }} / {{ totalPages }}
      </span>
      <button
        type="button"
        @click="emit('update:currentPage', currentPage + 1)"
        :disabled="currentPage === totalPages"
        class="px-3 py-1.5 rounded-md text-[13px] font-medium border border-[#C9CCCF] bg-white text-[#202223] disabled:opacity-50 disabled:cursor-not-allowed"
      >
        Berikutnya
      </button>
    </div>
  </div>
</template>
